# Generated by Django 3.2.6 on 2021-10-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('pages', models.PositiveIntegerField()),
            ],
        ),
    ]
