# Generated by Django 3.2.6 on 2021-10-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('hr', 'hr'), ('faculty', 'faculty'), ('counsillor', 'counsillor')], default='faculty', max_length=30),
        ),
    ]
